title: My Site
description: My sample web site ready for editing
styles:
  - /styles.css
  - https://cdn.jsdelivr.net/npm/prismjs@1/themes/prism-tomorrow.min.css
  - https://cdn.jsdelivr.net/npm/prismjs@1/plugins/treeview/prism-treeview.min.css
  - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@7/css/all.min.css
scripts:
  - https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-core.min.js
  - https://cdn.jsdelivr.net/npm/prismjs@1/plugins/autoloader/prism-autoloader.min.js
  - https://cdn.jsdelivr.net/npm/prismjs@1/plugins/treeview/prism-treeview.min.js
footer: |-
  This is base <a href="https://github.com/johnheenan/minform" target="_blank">Minform Template</a> v{% npm_package_version %}.
  This footer can span multiple lines in `site-1/_data/site.yml` but can display as one line or more across full width. Markdown can be included in footer.

#corsprod: set true to use cors in production
corsprod: true

#nohtmx: set to true if form submssion fails, otherwise set to false or convert to comment
#nohtmx: true

#corsurl: set to server url if using cors, otherwise leave empty or as comment, hostfurl does not permit cors
corsurl: https://example.com
formpath: /somearbitrarycharacters
#formpath: /example@gmail.com

